# Generated by Django 2.1.2 on 2022-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='myinput',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='入力文字'),
        ),
        migrations.AddField(
            model_name='item',
            name='myresult',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='結果'),
        ),
    ]
